### ISSUE TITLE
js extension in typsecript file

### ISSUE THREAD

**Issue by pnaik1** [obs-nebula/bdi-ts#2]
Hello @helio-frota , I was getting error after compiling and starting the application (that the module is not found) it was caused beacuse of no extension in the typescript file , I tried using ts extension but it throws an error, then I used js extension in typescript file and it worked fine , I have pushed it in main , Can you please cross check and tell me is it the right way to do?

**Comment by helio-frota** [comment]
@pnaik1 I saw the code, we need to remove the `.js` extension from the imports.

I don't know what is the error probably something with ESM.

**Comment by helio-frota** [comment]
@pnaik1 also the `index.js` still using `.js` extension

**Comment by helio-frota** [comment]
@pnaik1 I pushed changes to the main please update and we can continue from there.

**Comment by helio-frota** [comment]
@pnaik1 given the purpose of this project probably make no sense for us to transpile to js under the dist directory, since we have no plans to publish or make that as general use like a CLI or lib.

https://stackoverflow.com/questions/63742790/unable-to-import-esm-ts-module-in-node/65163089#65163089

So you can make use of ts-node to continue playing with TypeScript instead of worry about transpilation process to the final destination (dist).

https://github.com/TypeStrong/ts-node

**Comment by pnaik1** [comment]
okay @helio-frota I will try that

**Comment by pnaik1** [comment]
@helio-frota made the changes and working fine , Thank you

**Comment by pnaik1** [comment]
@helio-frota , I found that index.ts file was inside the src directory , but in the original repository it should be outside the src directory , so I made the chnages and pushed  it to the main

**Comment by helio-frota** [comment]
@pnaik1 not a problem I saw those things in the past when trying to migrate from js to ts. 
but the standard is to keep everything inside `src` :

2 examples:
* https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-core/src
* https://github.com/cloudevents/sdk-javascript/tree/main/src

**Comment by helio-frota** [comment]
I pushed the working code to the main branch.
That was really a x thing depending on y which depends on z and etc.

I decided to start using a basic configuration I added to this repo here: https://github.com/helio-frota/infinispan-js-client-ts-support-test/blob/main/package.json#L6

And then I started to see the errors which at the end was caused by the top-level await used inside the `bdi.ts` file that was incompatible with the config and then I found this https://stackoverflow.com/questions/64610476/nodejs-typescript-ts-node-dev-top-level-await which contains updated information for node 18.x

so yeah we can run the tests and start the app and able to continue playing with TS :+1:
